trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'web-api-starter'
  dockerRegistryServiceConnection: '<your-docker-registry-service-connection>' # Replace with your Docker Registry service connection name

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push the Docker image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(Build.BuildId)
          latest
